# Extracting Variable and Value Labels

We will need to know what the numbers mean to know what to do next for processing or analysis.
We will extract this information from the SPSS syntax files.
There are two procedures of interest:
1. `VARIABLE LABEL`: This describes what the variable measures or describes.
2. `VALUE LABEL`: This describes what each code value used in that variable means.

In [1]:
import pandas as pd
import re

# 0. List of Syntax Files

The syntax file request result metadata conveniently also serves as a reminder of the names that the files have been stored as.

In [2]:
syntax_files = pd.read_csv('data/request_result_syntax.csv', index_col=[0])
syntax_files

,persistentId,description,num_fails
syntax_1999-nov-dec_rebase2001.txt,hdl:11272.1/AB2/LGGEKU/FI1VWQ,SPSS syntax November-December 1999,0
syntax_1999-jan-oct_rebase2001.txt,hdl:11272.1/AB2/LGGEKU/FFZGU0,SPSS syntax January-October 1999,0
syntax_2000-2010_rebase2001.txt,hdl:11272.1/AB2/F0G05L/DKBI2F,SPSS syntax 2000-2010,0
syntax_1987-1998_rebase2001.txt,hdl:11272.1/AB2/PW64LJ/MVVTLK,SPSS syntax 1987-1998,0
syntax_1976-1986_rebase2001.txt,hdl:11272.1/AB2/SS4B9S/RU28Z5,SPSS syntax 1971-1986,0
syntax_2022_rebase2023.txt,hdl:11272.1/AB2/SRAU7E/S0JZL7,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2021_rebase2023.txt,hdl:11272.1/AB2/HP9TEK/7UJJRS,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2020_rebase2023.txt,hdl:11272.1/AB2/GGXMM2/X7TBKH,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2019_rebase2023.txt,hdl:11272.1/AB2/ATGWRX/K75CHT,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2018_rebase2023.txt,hdl:11272.1/AB2/CFRSC0/GSGTYS,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2017_rebase2023.txt,hdl:11272.1/AB2/PO8CWI/QNDQKZ,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2016_rebase2023.txt,hdl:11272.1/AB2/SRHMXU/HJAGNN,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2015_rebase2023.txt,hdl:11272.1/AB2/N1N5S6/5AI29G,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2014_rebase2023.txt,hdl:11272.1/AB2/B9RMKT/OSX0NY,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2013_rebase2023.txt,hdl:11272.1/AB2/1CUHBA/E9CWFD,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2012_rebase2023.txt,hdl:11272.1/AB2/VRMXQC/AHABNO,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2011_rebase2023.txt,hdl:11272.1/AB2/GK3SFF/AJRDXI,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2010_rebase2023.txt,hdl:11272.1/AB2/MWQWLP/HQHKFZ,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2009_rebase2023.txt,hdl:11272.1/AB2/B43KX7/RQ2UE1,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2008_rebase2023.txt,hdl:11272.1/AB2/LA3WXI/RQU1WN,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2007_rebase2023.txt,hdl:11272.1/AB2/NANO81/ITTWHL,SPSS syntax for plain-text microdata files. Cr...,0
syntax_2006_rebase2023.txt,hdl:11272.1/AB2/0B5LPL/AW8WZP,SPSS syntax for plain-text microdata files. Cr...,0

We will process the files in reverse chronological order: from most recent to oldest, from latest rebase version to last.

In [3]:
syntax_files = syntax_files.index.tolist()
syntax_files = sorted(syntax_files, key=lambda f: f.split('_')[1], reverse=True)
print(syntax_files)

['syntax_2022_rebase2023.txt', 'syntax_2021_rebase2023.txt', 'syntax_2020_rebase2023.txt', 'syntax_2019_rebase2023.txt', 'syntax_2018_rebase2023.txt', 'syntax_2017_rebase2023.txt', 'syntax_2016_rebase2023.txt', 'syntax_2015_rebase2023.txt', 'syntax_2014_rebase2023.txt', 'syntax_2013_rebase2023.txt', 'syntax_2012_rebase2023.txt', 'syntax_2011_rebase2023.txt', 'syntax_2010_rebase2023.txt', 'syntax_2009_rebase2023.txt', 'syntax_2008_rebase2023.txt', 'syntax_2007_rebase2023.txt', 'syntax_2006_rebase2023.txt', 'syntax_2000-2010_rebase2001.txt', 'syntax_1999-nov-dec_rebase2001.txt', 'syntax_1999-jan-oct_rebase2001.txt', 'syntax_1987-1998_rebase2001.txt', 'syntax_1976-1986_rebase2001.txt']

# 1. Test Run Extraction Procedure

We will show using one example how the procedure works.
First we define all the regex patterns that will be used to extract the needed information.

In [4]:
proc_re = {
    'varlab': re.compile(r'variable\s+label(?:"[^"]+"|\'[^\']+\'|[^\.])+?\.', flags=re.I),
    'varlab_var': re.compile(r'/?\W*([a-zA-Z0-9_]+)\s*(?:"(.+?)"|\'(.+?)\')', flags=re.I),
    'vallab': re.compile(r'value\s+label(?:".+?"|\'.+?\'|[^\.])+?\.', flags=re.I),
    'vallab_var': re.compile(r'/\W*([a-zA-Z0-9_]+)((?:".+?"|\'.+?\'|[^/])+)', flags=re.I),
    'vallab_lab': re.compile(r'(?:([0-9]+)\s*(?i:"(.+?)"|\'(.+?)\'))', flags=re.I)
}

We load a syntax file and show an example printout of what SPSS syntax code looks like.

In [5]:
syntax = str()
with open('data/{}'.format(syntax_files[0]), 'rt', encoding='utf-8-sig') as f:
    syntax = f.read()
print(syntax[:200])

SET UNICODE YES.

COMMENT Formatted as per Statcan PRN.

DATA LIST FILE="pubMM22.prn"
/REC_NUM 1-7
SURVYEAR 8-11
SURVMNTH 12-13
LFSSTAT 14-14
PROV 15-16
CMA 17-17
AGE_12 18-19
AGE_6 20-20
SEX 21-21
M

We extract the `VARIABLE LABEL` procedure from the loaded syntax file and show an example printout of this command.

In [6]:
varlab_syntax = proc_re['varlab'].search(syntax).group(0)
print(varlab_syntax)

VARIABLE LABELS
REC_NUM 'Order of record in file'
/SURVYEAR 'Survey year'
/SURVMNTH 'Survey month'
/LFSSTAT 'Labour force status'
/PROV 'Province'
/CMA 'Nine largest CMAs'
/AGE_12 'Five-year age group of respondent'
/AGE_6 'Age in 2 and 3 year groups, 15 to 29'
/SEX 'Sex of respondent'
/MARSTAT 'Marital status of respondent'
/EDUC 'Highest educational attainment'
/MJH 'Single or multiple jobholder'
/EVERWORK 'Not currently employed, worked in the past'
/FTPTLAST 'Full- or part-time status of last job'
/COWMAIN 'Class of worker, main job'
/IMMIG 'Immigrant status'
/NAICS_21 'Industry of main job'
/NOC_10 'Occupation at main job'
/NOC_43 'Occupation at main job'
/YABSENT 'Reason of absence, full week'
/WKSAWAY 'Number of weeks absent from work'
/PAYAWAY 'Paid for time off, full-week absence only'
/UHRSMAIN 'Usual hours worked per week at main job'
/AHRSMAIN 'Actual hours worked per week at main job'
/FTPTMAIN 'Full- or part-time status at main or only job'
/UTOTHRS 'Usual hours worked per week at all jobs'
/ATOTHRS 'Actual hours worked per week at all jobs'
/HRSAWAY 'Hours away from work, part-week absence only'
/YAWAY 'Reason for part-week absence'
/PAIDOT 'Paid overtime hours in reference week'
/UNPAIDOT 'Unpaid overtime hours in reference week'
/XTRAHRS 'Number of overtime or extra hours worked'
/WHYPT 'Reason for part-time work'
/TENURE 'Job tenure with current employer (months)'
/PREVTEN 'Job tenure with previous employer (months)'
/HRLYEARN 'Usual hourly wages, employees only'
/UNION 'Union status, employees only'
/PERMTEMP 'Job permanency, employees only'
/ESTSIZE 'Establishment size'
/FIRMSIZE 'Firm size'
/DURUNEMP 'Duration of unemployment (weeks)'
/FLOWUNEM 'Flows into unemployment'
/UNEMFTPT 'Unemployed, type of job wanted'
/WHYLEFTO 'Reason for leaving job during previous year'
/WHYLEFTN 'Reason for leaving job during previous year'
/DURJLESS 'Duration of joblessness (months)'
/AVAILABL 'Availability during the reference week'
/LKPUBAG 'Unemployed, used public employment agency'
/LKEMPLOY 'Unemployed, checked with employers directly'
/LKRELS 'Unemployed, checked with friends or relatives'
/LKATADS 'Unemployed, looked at job ads'
/LKANSADS 'Unemployed, placed or answered ads'
/LKOTHERN 'Unemployed, other methods'
/PRIORACT 'Main activity before started looking for work'
/YNOLOOK 'Reason for not looking for work during the reference week'
/TLOLOOK 'Temporary layoff, looked for work during the last four weeks'
/SCHOOLN 'Current student status'
/EFAMTYPE 'Type of economic family'
/AGYOWNK 'Age of youngest child'
/FINALWT 'Standard final weight'.

We extract the variable names and labels into a dictionary and show an example of what the final result looks like.

In [7]:
varlab_syntax = proc_re['varlab_var'].findall(varlab_syntax)
varlab_syntax = {v: a if a else b for v, a, b in varlab_syntax}
varlab_syntax

{'REC_NUM': 'Order of record in file',
 'SURVYEAR': 'Survey year',
 'SURVMNTH': 'Survey month',
 'LFSSTAT': 'Labour force status',
 'PROV': 'Province',
 'CMA': 'Nine largest CMAs',
 'AGE_12': 'Five-year age group of respondent',
 'AGE_6': 'Age in 2 and 3 year groups, 15 to 29',
 'SEX': 'Sex of respondent',
 'MARSTAT': 'Marital status of respondent',
 'EDUC': 'Highest educational attainment',
 'MJH': 'Single or multiple jobholder',
 'EVERWORK': 'Not currently employed, worked in the past',
 'FTPTLAST': 'Full- or part-time status of last job',
 'COWMAIN': 'Class of worker, main job',
 'IMMIG': 'Immigrant status',
 'NAICS_21': 'Industry of main job',
 'NOC_10': 'Occupation at main job',
 'NOC_43': 'Occupation at main job',
 'YABSENT': 'Reason of absence, full week',
 'WKSAWAY': 'Number of weeks absent from work',
 'PAYAWAY': 'Paid for time off, full-week absence only',
 'UHRSMAIN': 'Usual hours worked per week at main job',
 'AHRSMAIN': 'Actual hours worked per week at main job',
 'FTPTMAIN': 'Full- or part-time status at main or only job',
 'UTOTHRS': 'Usual hours worked per week at all jobs',
 'ATOTHRS': 'Actual hours worked per week at all jobs',
 'HRSAWAY': 'Hours away from work, part-week absence only',
 'YAWAY': 'Reason for part-week absence',
 'PAIDOT': 'Paid overtime hours in reference week',
 'UNPAIDOT': 'Unpaid overtime hours in reference week',
 'XTRAHRS': 'Number of overtime or extra hours worked',
 'WHYPT': 'Reason for part-time work',
 'TENURE': 'Job tenure with current employer (months)',
 'PREVTEN': 'Job tenure with previous employer (months)',
 'HRLYEARN': 'Usual hourly wages, employees only',
 'UNION': 'Union status, employees only',
 'PERMTEMP': 'Job permanency, employees only',
 'ESTSIZE': 'Establishment size',
 'FIRMSIZE': 'Firm size',
 'DURUNEMP': 'Duration of unemployment (weeks)',
 'FLOWUNEM': 'Flows into unemployment',
 'UNEMFTPT': 'Unemployed, type of job wanted',
 'WHYLEFTO': 'Reason for leaving job during previous year',
 'WHYLEFTN': 'Reason for leaving job during previous year',
 'DURJLESS': 'Duration of joblessness (months)',
 'AVAILABL': 'Availability during the reference week',
 'LKPUBAG': 'Unemployed, used public employment agency',
 'LKEMPLOY': 'Unemployed, checked with employers directly',
 'LKRELS': 'Unemployed, checked with friends or relatives',
 'LKATADS': 'Unemployed, looked at job ads',
 'LKANSADS': 'Unemployed, placed or answered ads',
 'LKOTHERN': 'Unemployed, other methods',
 'PRIORACT': 'Main activity before started looking for work',
 'YNOLOOK': 'Reason for not looking for work during the reference week',
 'TLOLOOK': 'Temporary layoff, looked for work during the last four weeks',
 'SCHOOLN': 'Current student status',
 'EFAMTYPE': 'Type of economic family',
 'AGYOWNK': 'Age of youngest child',
 'FINALWT': 'Standard final weight'}

We extract the `VALUE LABEL` procedure and show an example printout of what this command looks like.

In [8]:
vallab_syntax = proc_re['vallab'].search(syntax).group(0)
print(vallab_syntax)

VALUE LABELS
REC_NUM
/SURVYEAR
/SURVMNTH
 1 "January"
 2 "February"
 3 "March"
 4 "April"
 5 "May"
 6 "June"
 7 "July"
 8 "August"
 9 "September"
 10 "October"
 11 "November"
 12 "December"
/ LFSSTAT
 1 "Employed, at work"
 2 "Employed, absent from work"
 3 "Unemployed"
 4 "Not in labour force"
/PROV
 10 "Newfoundland and Labrador"
 11 "Prince Edward Island"
 12 "Nova Scotia"
 13 "New Brunswick"
 24 "Quebec"
 35 "Ontario"
 46 "Manitoba"
 47 "Saskatchewan"
 48 "Alberta"
 59 "British Columbia"
/CMA
 1 "Québec"
 2 "Montréal"
 3 "Ottawa–Gatineau (Ontario part)"
 4 "Toronto"
 5 "Hamilton"
 6 "Winnipeg"
 7 "Calgary"
 8 "Edmonton"
 9 "Vancouver"
 0 "Other CMA or non-CMA"
/AGE_12
 01 "15 to 19 years"
 02 "20 to 24 years"
 03 "25 to 29 years"
 04 "30 to 34 years"
 05 "35 to 39 years"
 06 "40 to 44 years"
 07 "45 to 49 years"
 08 "50 to 54 years"
 09 "55 to 59 years"
 10 "60 to 64 years"
 11 "65 to 69 years"
 12 "70 and over"
/AGE_6
 1 "15 to 16 years"
 2 "17 to 19 years"
 3 "20 to 21 years"
 4 "22 to 24 years"
 5 "25 to 26 years"
 6 "27 to 29 years"
/SEX
 1 "Male"
 2 "Female"
/MARSTAT
 1 "Married"
 2 "Living in common-law"
 3 "Widowed"
 4 "Separated"
 5 "Divorced"
 6 "Single, never married"
/EDUC
 0 "0 to 8 years"
 1 "Some high school"
 2 "High school graduate"
 3 "Some postsecondary"
 4 "Postsecondary certificate or diploma"
 5 "Bachelor's degree"
 6 "Above bachelor's degree"
/MJH
 1 "Single jobholder, including job changers"
 2 "Multiple jobholder"
/EVERWORK
 1 "Yes, within last year"
 2 "Yes, more than 1 year ago"
 3 "No, never worked"
/FTPTLAST
 1 "Full-time (30 hours or more)"
 2 "Part-time (1 to 29 hours)"
/COWMAIN
 1 "Public sector employees"
 2 "Private sector employees"
 3 "Self-employed incorporated, with paid help"
 4 "Self-employed incorporated, no paid help"
 5 "Self-employed unincorporated, with paid help"
 6 "Self-employed unincorporated, no paid help"
 7 "Unpaid family worker"
/IMMIG
 1 "Immigrant, landed 10 or less years earlier"
 2 "Immigrant, landed more than 10 years earlier"
 3 "Non-immigrant"
/NAICS_21
 01 "Agriculture"
 02 "Forestry and logging and support activities for forestry"
 03 "Fishing, hunting and trapping"
 04 "Mining, quarrying, and oil and gas extraction"
 05 "Utilities"
 06 "Construction"
 07 "Manufacturing - durable goods"
 08 "Manufacturing - non-durable goods"
 09 "Wholesale trade"
 10 "Retail trade"
 11 "Transportation and warehousing"
 12 "Finance and insurance"
 13 "Real estate and rental and leasing"
 14 "Professional, scientific and technical services"
 15 "Business, building and other support services"
 16 "Educational services"
 17 "Health care and social assistance"
 18 "Information, culture and recreation"
 19 "Accommodation and food services"
 20 "Other services (except public administration)"
 21 "Public administration"
/NOC_10
 01 "Management occupations"
 02 "Business, finance and administration occupations"
 03 "Natural and applied sciences and related occupations"
 04 "Health occupations"
 05 "Occupations in education, law and social, community and government services"
 06 "Occupations in art, culture, recreation and sport"
 07 "Sales and service occupations"
 08 "Trades, transport and equipment operators and related occupations"
 09 "Natural resources, agriculture and related production occupations"
 10 "Occupations in manufacturing and utilities"
/NOC_43
 01 "Senior management occupations"
 02 "Specialized middle management occupations"
 03 "Middle management occupations in retail and wholesale trade and customer services"
 04 "Middle management occupations in trades, transportation, production and utilities"
 05 "Professional occupations in business and finance"
 06 "Administrative and financial supervisors and administrative occupations"
 07 "Finance, insurance and related business administrative occupations"
 08 "Office support occupations"
 09 "Distribution, tracking and scheduling co-ordination occupations"
 10 "Professional occupations in natural and applied sciences"
 11 "Technical occupations related to natural and applied sciences"
 12 "Professional occupations in nursing"
 13 "Professional occupations in health (except nursing)"
 14 "Technical occupations in health"
 15 "Assisting occupations in support of health services"
 16 "Professional occupations in education services"
 17 "Professional occupations in law and social, community and government services"
 18 "Paraprofessional occupations in legal, social, community and education services"
 19 "Occupations in front-line public protection services"
 20 "Care providers and educational, legal and public protection support occupations"
 21 "Professional occupations in art and culture"
 22 "Technical occupations in art, culture, recreation and sport"
 23 "Retail sales supervisors and specialized sales occupations"
 24 "Service supervisors and specialized service occupations"
 25 "Sales representatives and salespersons - wholesale and retail trade"
 26 "Service representatives and other customer and personal services occupations"
 27 "Sales support occupations"
 28 "Service support and other service occupations, n.e.c."
 29 "Industrial, electrical and construction trades"
 30 "Maintenance and equipment operation trades"
 31 "Other installers, repairers and servicers and material handlers"
 32 "Transport and heavy equipment operation and related maintenance occupations"
 33 "Trades helpers, construction labourers and related occupations"
 34 "Supervisors and technical occupations in natural resources, agriculture and related production"
 35 "Workers in natural resources, agriculture and related production"
 36 "Harvesting, landscaping and natural resources labourers"
 37 "Processing, manufacturing and utilities supervisors and central control operators"
 38 "Processing and manufacturing machine operators and related production workers"
 39 "Assemblers in manufacturing"
 40 "Labourers in processing, manufacturing and utilities"
/YABSENT
 0 "Other reasons"
 1 "Own illness or disability"
 2 "Personal or family responsibilities"
 3 "Vacation"
/WKSAWAY
/PAYAWAY
 1 "Yes"
 2 "No"
/UHRSMAIN
/AHRSMAIN
/FTPTMAIN
 1 "Full-time"
 2 "Part-time"
/UTOTHRS
/ATOTHRS
/HRSAWAY
/YAWAY
 0 "Other reasons"
 1 "Own illness or disability"
 2 "Personal or family responsibilities"
 3 "Vacation or civic holiday"
 4 "Working short-time"
/PAIDOT
/UNPAIDOT
/XTRAHRS
/WHYPT
 0 "Other reasons"
 1 "Own illness or disability"
 2 "Caring for children"
 3 "Other personal or family responsibilities"
 4 "Going to school"
 5 "Personal preference"
 6 "Business conditions or could not find full-time work, looked for full-time work in last month"
 7 "Business conditions or could not find full-time work, did not look for full-time work in last month"
/TENURE
/PREVTEN
/HRLYEARN
/UNION
 1 "Union member"
 2 "Not a member but covered by a union contract or collective agreement"
 3 "Non-unionized"
/PERMTEMP
 1 "Permanent"
 2 "Temporary, seasonal job"
 3 "Temporary, term or contract job"
 4 "Temporary, casual or other temorary jobs"
/ESTSIZE
 1 "Less than 20 employees"
 2 "20 to 99 employees"
 3 "100 to 500 employees"
 4 "More than 500 employees"
/FIRMSIZE
 1 "Less than 20 employees"
 2 "20 to 99 employees"
 3 "100 to 500 employees"
 4 "More than 500 employees"
/DURUNEMP
/FLOWUNEM
 1 "Job losers, temporary layoff"
 2 "Job losers, permanent layoff"
 3 "Job leavers"
 4 "Job leavers/losers (status unknown), worked more than 1 year ago"
 5 "New entrants"
 6 "Re-entrants, worked 1 year ago or less"
 7 "Re-entrants, worked more than 1 year ago"
 8 "Future starts"
/UNEMFTPT
 1 "Full-time"
 2 "Part-time"
 3 "Future starts"
/WHYLEFTO
 0 "Job leavers, other reasons"
 1 "Job leavers, own illness or disability"
 2 "Job leavers, personal or family responsibilities"
 3 "Job leavers, going to school"
 4 "Job losers, laid off"
 5 "Job leavers, retired"
/WHYLEFTN
 00 "Job leavers, other reasons"
 01 "Job leavers, own illness or disability"
 02 "Job leavers, caring for children"
 03 "Job leavers, pregnancy"
 04 "Job leavers, personal or family responsibilities"
 05 "Job leavers, going to school"
 06 "Job leavers, dissatisfied"
 07 "Job leavers, retired"
 08 "Job leavers, business sold or closed down (self-employed)"
 09 "Job losers, end of seasonal job (employee)"
 10 "Job losers, end of temporary or casual (employee)"
 11 "Job losers, company moved or out of business (employee)"
 12 "Job losers, business conditions (employee)"
 13 "Job losers, dismissal or other reasons"
/DURJLESS
/AVAILABL
 1 "Not available"
 2 "Yes, available"
/LKPUBAG
 1 "Yes"
/LKEMPLOY
 1 "Yes"
/LKRELS
 1 "Yes"
/LKATADS
 1 "Yes"
/LKANSADS
 1 "Yes"
/LKOTHERN
 1 "Yes"
/PRIORACT
 0 "Other"
 1 "Working"
 2 "Managing a home"
 3 "Going to school"
/YNOLOOK
 0 "Wanted work, reason - other"
 1 "Wanted work, reason - own illness or disability"
 2 "Wanted work, reason - caring for children"
 3 "Wanted work, reason - other personal or family responsibilities"
 4 "Wanted work, reason - school"
 5 "Wanted work, reason - awaiting recall or reply"
 6 "Wanted work, reason - discouraged"
/TLOLOOK
 1 "Yes"
 2 "No"
/SCHOOLN
 1 "Non-student"
 2 "Full-time student"
 3 "Part-time student"
/EFAMTYPE
 01 "Person not in an economic family"
 02 "Dual-earner couple, no children or none under 25"
 03 "Dual-earner couple, youngest child 0 to 17"
 04 "Dual-earner couple, youngest child 18 to 24"
 05 "Single-earner couple, male employed, no children or none under 25"
 06 "Single-earner couple, male employed, youngest child 0 to 17"
 07 "Single-earner couple, male employed, youngest child 18 to 24"
 08 "Single-earner couple, female employed, no children or none under 25"
 09 "Single-earner couple, female employed, youngest child 0 to 17"
 10 "Single-earner couple, female employed, youngest child 18 to 24"
 11 "Non-earner couple, no children or none under 25"
 12 "Non-earner couple, youngest child 0 to 17"
 13 "Non-earner couple, youngest child 18 to 24"
 14 "Lone-parent family, parent employed, youngest child 0 to 17"
 15 "Lone-parent family, parent employed, youngest child 18 to 24"
 16 "Lone-parent family, parent not employed, youngest child 0 to 17"
 17 "Lone-parent family, parent not employed, youngest child 18 to 24"
 18 "Other families"
/AGYOWNK
 1 "Youngest child less than 6 years"
 2 "Youngest child 6 to 12 years"
 3 "Youngest child 13 to 17 years"
 4 "Youngest child 18 to 24 years"
/FINALWT
/.

We will proceed with information extraction in two steps.
First we extract the variable names and value labels as a single string and show what the output looks like.

In [9]:
vallab_syntax = proc_re['vallab_var'].findall(vallab_syntax)
vallab_syntax = {v: l for v, l in vallab_syntax}
vallab_syntax

{'SURVYEAR': '\n',
 'SURVMNTH': '\n 1 "January"\n 2 "February"\n 3 "March"\n 4 "April"\n 5 "May"\n 6 "June"\n 7 "July"\n 8 "August"\n 9 "September"\n 10 "October"\n 11 "November"\n 12 "December"\n',
 'LFSSTAT': '    \n 1 "Employed, at work"\n 2 "Employed, absent from work"\n 3 "Unemployed"\n 4 "Not in labour force"\n',
 'PROV': '\n 10 "Newfoundland and Labrador"\n 11 "Prince Edward Island"\n 12 "Nova Scotia"\n 13 "New Brunswick"\n 24 "Quebec"\n 35 "Ontario"\n 46 "Manitoba"\n 47 "Saskatchewan"\n 48 "Alberta"\n 59 "British Columbia"\n',
 'CMA': '\n 1 "Québec"\n 2 "Montréal"\n 3 "Ottawa–Gatineau (Ontario part)"\n 4 "Toronto"\n 5 "Hamilton"\n 6 "Winnipeg"\n 7 "Calgary"\n 8 "Edmonton"\n 9 "Vancouver"\n 0 "Other CMA or non-CMA"\n',
 'AGE_12': '\n 01 "15 to 19 years"\n 02 "20 to 24 years"\n 03 "25 to 29 years"\n 04 "30 to 34 years"\n 05 "35 to 39 years"\n 06 "40 to 44 years"\n 07 "45 to 49 years"\n 08 "50 to 54 years"\n 09 "55 to 59 years"\n 10 "60 to 64 years"\n 11 "65 to 69 years"\n 12 "70 and over"\n',
 'AGE_6': '    \n 1 "15 to 16 years"\n 2 "17 to 19 years"\n 3 "20 to 21 years"\n 4 "22 to 24 years"\n 5 "25 to 26 years"\n 6 "27 to 29 years"\n',
 'SEX': '\n 1 "Male"\n 2 "Female"\n',
 'MARSTAT': '\n 1 "Married"\n 2 "Living in common-law"\n 3 "Widowed"\n 4 "Separated"\n 5 "Divorced"\n 6 "Single, never married"\n',
 'EDUC': '\n 0 "0 to 8 years"\n 1 "Some high school"\n 2 "High school graduate"\n 3 "Some postsecondary"\n 4 "Postsecondary certificate or diploma"\n 5 "Bachelor\'s degree"\n 6 "Above bachelor\'s degree"\n',
 'MJH': '\n 1 "Single jobholder, including job changers"\n 2 "Multiple jobholder"\n',
 'EVERWORK': '\n 1 "Yes, within last year"\n 2 "Yes, more than 1 year ago"\n 3 "No, never worked"\n',
 'FTPTLAST': '\n 1 "Full-time (30 hours or more)"\n 2 "Part-time (1 to 29 hours)"\n',
 'COWMAIN': '\n 1 "Public sector employees"\n 2 "Private sector employees"\n 3 "Self-employed incorporated, with paid help"\n 4 "Self-employed incorporated, no paid help"\n 5 "Self-employed unincorporated, with paid help"\n 6 "Self-employed unincorporated, no paid help"\n 7 "Unpaid family worker"\n',
 'IMMIG': '\n 1 "Immigrant, landed 10 or less years earlier"\n 2 "Immigrant, landed more than 10 years earlier"\n 3 "Non-immigrant"\n',
 'NAICS_21': '\n 01 "Agriculture"\n 02 "Forestry and logging and support activities for forestry"\n 03 "Fishing, hunting and trapping"\n 04 "Mining, quarrying, and oil and gas extraction"\n 05 "Utilities"\n 06 "Construction"\n 07 "Manufacturing - durable goods"\n 08 "Manufacturing - non-durable goods"\n 09 "Wholesale trade"\n 10 "Retail trade"\n 11 "Transportation and warehousing"\n 12 "Finance and insurance"\n 13 "Real estate and rental and leasing"\n 14 "Professional, scientific and technical services"\n 15 "Business, building and other support services"\n 16 "Educational services"\n 17 "Health care and social assistance"\n 18 "Information, culture and recreation"\n 19 "Accommodation and food services"\n 20 "Other services (except public administration)"\n 21 "Public administration"\n',
 'NOC_10': '    \n 01 "Management occupations"\n 02 "Business, finance and administration occupations"\n 03 "Natural and applied sciences and related occupations"\n 04 "Health occupations"\n 05 "Occupations in education, law and social, community and government services"\n 06 "Occupations in art, culture, recreation and sport"\n 07 "Sales and service occupations"\n 08 "Trades, transport and equipment operators and related occupations"\n 09 "Natural resources, agriculture and related production occupations"\n 10 "Occupations in manufacturing and utilities"\n',
 'NOC_43': '    \n 01 "Senior management occupations"\n 02 "Specialized middle management occupations"\n 03 "Middle management occupations in retail and wholesale trade and customer services"\n 04 "Middle management occupations in trades, transportation, production and utilities"\n 05 "Professional occupations in business and finance"\n 06 "Administrative and financial supervisors and administrative occupations"\n 07 "Finance, insurance and related business administrative occupations"\n 08 "Office support occupations"\n 09 "Distribution, tracking and scheduling co-ordination occupations"\n 10 "Professional occupations in natural and applied sciences"\n 11 "Technical occupations related to natural and applied sciences"\n 12 "Professional occupations in nursing"\n 13 "Professional occupations in health (except nursing)"\n 14 "Technical occupations in health"\n 15 "Assisting occupations in support of health services"\n 16 "Professional occupations in education services"\n 17 "Professional occupations in law and social, community and government services"\n 18 "Paraprofessional occupations in legal, social, community and education services"\n 19 "Occupations in front-line public protection services"\n 20 "Care providers and educational, legal and public protection support occupations"\n 21 "Professional occupations in art and culture"\n 22 "Technical occupations in art, culture, recreation and sport"\n 23 "Retail sales supervisors and specialized sales occupations"\n 24 "Service supervisors and specialized service occupations"\n 25 "Sales representatives and salespersons - wholesale and retail trade"\n 26 "Service representatives and other customer and personal services occupations"\n 27 "Sales support occupations"\n 28 "Service support and other service occupations, n.e.c."\n 29 "Industrial, electrical and construction trades"\n 30 "Maintenance and equipment operation trades"\n 31 "Other installers, repairers and servicers and material handlers"\n 32 "Transport and heavy equipment operation and related maintenance occupations"\n 33 "Trades helpers, construction labourers and related occupations"\n 34 "Supervisors and technical occupations in natural resources, agriculture and related production"\n 35 "Workers in natural resources, agriculture and related production"\n 36 "Harvesting, landscaping and natural resources labourers"\n 37 "Processing, manufacturing and utilities supervisors and central control operators"\n 38 "Processing and manufacturing machine operators and related production workers"\n 39 "Assemblers in manufacturing"\n 40 "Labourers in processing, manufacturing and utilities"\n',
 'YABSENT': '\n 0 "Other reasons"\n 1 "Own illness or disability"\n 2 "Personal or family responsibilities"\n 3 "Vacation"\n',
 'WKSAWAY': '\n',
 'PAYAWAY': '\n 1 "Yes"\n 2 "No"\n',
 'UHRSMAIN': '\n',
 'AHRSMAIN': '\n',
 'FTPTMAIN': '\n 1 "Full-time"\n 2 "Part-time"\n',
 'UTOTHRS': '\n',
 'ATOTHRS': '\n',
 'HRSAWAY': '\n',
 'YAWAY': '\n 0 "Other reasons"\n 1 "Own illness or disability"\n 2 "Personal or family responsibilities"\n 3 "Vacation or civic holiday"\n 4 "Working short-time"\n',
 'PAIDOT': '\n',
 'UNPAIDOT': '\n',
 'XTRAHRS': '\n',
 'WHYPT': '\n 0 "Other reasons"\n 1 "Own illness or disability"\n 2 "Caring for children"\n 3 "Other personal or family responsibilities"\n 4 "Going to school"\n 5 "Personal preference"\n 6 "Business conditions or could not find full-time work, looked for full-time work in last month"\n 7 "Business conditions or could not find full-time work, did not look for full-time work in last month"\n',
 'TENURE': '\n',
 'PREVTEN': '\n',
 'HRLYEARN': '\n',
 'UNION': '\n 1 "Union member"\n 2 "Not a member but covered by a union contract or collective agreement"\n 3 "Non-unionized"\n',
 'PERMTEMP': '\n 1 "Permanent"\n 2 "Temporary, seasonal job"\n 3 "Temporary, term or contract job"\n 4 "Temporary, casual or other temorary jobs"\n',
 'ESTSIZE': '\n 1 "Less than 20 employees"\n 2 "20 to 99 employees"\n 3 "100 to 500 employees"\n 4 "More than 500 employees"\n',
 'FIRMSIZE': '\n 1 "Less than 20 employees"\n 2 "20 to 99 employees"\n 3 "100 to 500 employees"\n 4 "More than 500 employees"\n',
 'DURUNEMP': '\n',
 'FLOWUNEM': '\n 1 "Job losers, temporary layoff"\n 2 "Job losers, permanent layoff"\n 3 "Job leavers"\n 4 "Job leavers/losers (status unknown), worked more than 1 year ago"\n 5 "New entrants"\n 6 "Re-entrants, worked 1 year ago or less"\n 7 "Re-entrants, worked more than 1 year ago"\n 8 "Future starts"\n',
 'UNEMFTPT': '\n 1 "Full-time"\n 2 "Part-time"\n 3 "Future starts"\n',
 'WHYLEFTO': '\n 0 "Job leavers, other reasons"\n 1 "Job leavers, own illness or disability"\n 2 "Job leavers, personal or family responsibilities"\n 3 "Job leavers, going to school"\n 4 "Job losers, laid off"\n 5 "Job leavers, retired"\n',
 'WHYLEFTN': '\n 00 "Job leavers, other reasons"\n 01 "Job leavers, own illness or disability"\n 02 "Job leavers, caring for children"\n 03 "Job leavers, pregnancy"\n 04 "Job leavers, personal or family responsibilities"\n 05 "Job leavers, going to school"\n 06 "Job leavers, dissatisfied"\n 07 "Job leavers, retired"\n 08 "Job leavers, business sold or closed down (self-employed)"\n 09 "Job losers, end of seasonal job (employee)"\n 10 "Job losers, end of temporary or casual (employee)"\n 11 "Job losers, company moved or out of business (employee)"\n 12 "Job losers, business conditions (employee)"\n 13 "Job losers, dismissal or other reasons"\n',
 'DURJLESS': '\n',
 'AVAILABL': '\n 1 "Not available"\n 2 "Yes, available"\n',
 'LKPUBAG': '\n 1 "Yes"\n',
 'LKEMPLOY': '\n 1 "Yes"\n',
 'LKRELS': '\n 1 "Yes"\n',
 'LKATADS': '\n 1 "Yes"\n',
 'LKANSADS': '\n 1 "Yes"\n',
 'LKOTHERN': ' \n 1 "Yes"\n',
 'PRIORACT': '\n 0 "Other"\n 1 "Working"\n 2 "Managing a home"\n 3 "Going to school"\n',
 'YNOLOOK': '\n 0 "Wanted work, reason - other"\n 1 "Wanted work, reason - own illness or disability"\n 2 "Wanted work, reason - caring for children"\n 3 "Wanted work, reason - other personal or family responsibilities"\n 4 "Wanted work, reason - school"\n 5 "Wanted work, reason - awaiting recall or reply"\n 6 "Wanted work, reason - discouraged"\n',
 'TLOLOOK': '\n 1 "Yes"\n 2 "No"\n',
 'SCHOOLN': '\n 1 "Non-student"\n 2 "Full-time student"\n 3 "Part-time student"\n',
 'EFAMTYPE': '\n 01 "Person not in an economic family"\n 02 "Dual-earner couple, no children or none under 25"\n 03 "Dual-earner couple, youngest child 0 to 17"\n 04 "Dual-earner couple, youngest child 18 to 24"\n 05 "Single-earner couple, male employed, no children or none under 25"\n 06 "Single-earner couple, male employed, youngest child 0 to 17"\n 07 "Single-earner couple, male employed, youngest child 18 to 24"\n 08 "Single-earner couple, female employed, no children or none under 25"\n 09 "Single-earner couple, female employed, youngest child 0 to 17"\n 10 "Single-earner couple, female employed, youngest child 18 to 24"\n 11 "Non-earner couple, no children or none under 25"\n 12 "Non-earner couple, youngest child 0 to 17"\n 13 "Non-earner couple, youngest child 18 to 24"\n 14 "Lone-parent family, parent employed, youngest child 0 to 17"\n 15 "Lone-parent family, parent employed, youngest child 18 to 24"\n 16 "Lone-parent family, parent not employed, youngest child 0 to 17"\n 17 "Lone-parent family, parent not employed, youngest child 18 to 24"\n 18 "Other families"\n',
 'AGYOWNK': '\n 1 "Youngest child less than 6 years"\n 2 "Youngest child 6 to 12 years"\n 3 "Youngest child 13 to 17 years"\n 4 "Youngest child 18 to 24 years"\n',
 'FINALWT': '\n'}

Then from each string we extract the codes and code descriptions into a dictionary and show a printout of the final result.

In [10]:
vallab_syntax = {v: {int(n): a if a else b for n, a, b, in proc_re['vallab_lab'].findall(l)} for v, l in vallab_syntax.items()}
vallab_syntax

{'SURVYEAR': {},
 'SURVMNTH': {1: 'January',
  2: 'February',
  3: 'March',
  4: 'April',
  5: 'May',
  6: 'June',
  7: 'July',
  8: 'August',
  9: 'September',
  10: 'October',
  11: 'November',
  12: 'December'},
 'LFSSTAT': {1: 'Employed, at work',
  2: 'Employed, absent from work',
  3: 'Unemployed',
  4: 'Not in labour force'},
 'PROV': {10: 'Newfoundland and Labrador',
  11: 'Prince Edward Island',
  12: 'Nova Scotia',
  13: 'New Brunswick',
  24: 'Quebec',
  35: 'Ontario',
  46: 'Manitoba',
  47: 'Saskatchewan',
  48: 'Alberta',
  59: 'British Columbia'},
 'CMA': {1: 'Québec',
  2: 'Montréal',
  3: 'Ottawa–Gatineau (Ontario part)',
  4: 'Toronto',
  5: 'Hamilton',
  6: 'Winnipeg',
  7: 'Calgary',
  8: 'Edmonton',
  9: 'Vancouver',
  0: 'Other CMA or non-CMA'},
 'AGE_12': {1: '15 to 19 years',
  2: '20 to 24 years',
  3: '25 to 29 years',
  4: '30 to 34 years',
  5: '35 to 39 years',
  6: '40 to 44 years',
  7: '45 to 49 years',
  8: '50 to 54 years',
  9: '55 to 59 years',
  10: '60 to 64 years',
  11: '65 to 69 years',
  12: '70 and over'},
 'AGE_6': {1: '15 to 16 years',
  2: '17 to 19 years',
  3: '20 to 21 years',
  4: '22 to 24 years',
  5: '25 to 26 years',
  6: '27 to 29 years'},
 'SEX': {1: 'Male', 2: 'Female'},
 'MARSTAT': {1: 'Married',
  2: 'Living in common-law',
  3: 'Widowed',
  4: 'Separated',
  5: 'Divorced',
  6: 'Single, never married'},
 'EDUC': {0: '0 to 8 years',
  1: 'Some high school',
  2: 'High school graduate',
  3: 'Some postsecondary',
  4: 'Postsecondary certificate or diploma',
  5: "Bachelor's degree",
  6: "Above bachelor's degree"},
 'MJH': {1: 'Single jobholder, including job changers',
  2: 'Multiple jobholder'},
 'EVERWORK': {1: 'Yes, within last year',
  2: 'Yes, more than 1 year ago',
  3: 'No, never worked'},
 'FTPTLAST': {1: 'Full-time (30 hours or more)',
  2: 'Part-time (1 to 29 hours)'},
 'COWMAIN': {1: 'Public sector employees',
  2: 'Private sector employees',
  3: 'Self-employed incorporated, with paid help',
  4: 'Self-employed incorporated, no paid help',
  5: 'Self-employed unincorporated, with paid help',
  6: 'Self-employed unincorporated, no paid help',
  7: 'Unpaid family worker'},
 'IMMIG': {1: 'Immigrant, landed 10 or less years earlier',
  2: 'Immigrant, landed more than 10 years earlier',
  3: 'Non-immigrant'},
 'NAICS_21': {1: 'Agriculture',
  2: 'Forestry and logging and support activities for forestry',
  3: 'Fishing, hunting and trapping',
  4: 'Mining, quarrying, and oil and gas extraction',
  5: 'Utilities',
  6: 'Construction',
  7: 'Manufacturing - durable goods',
  8: 'Manufacturing - non-durable goods',
  9: 'Wholesale trade',
  10: 'Retail trade',
  11: 'Transportation and warehousing',
  12: 'Finance and insurance',
  13: 'Real estate and rental and leasing',
  14: 'Professional, scientific and technical services',
  15: 'Business, building and other support services',
  16: 'Educational services',
  17: 'Health care and social assistance',
  18: 'Information, culture and recreation',
  19: 'Accommodation and food services',
  20: 'Other services (except public administration)',
  21: 'Public administration'},
 'NOC_10': {1: 'Management occupations',
  2: 'Business, finance and administration occupations',
  3: 'Natural and applied sciences and related occupations',
  4: 'Health occupations',
  5: 'Occupations in education, law and social, community and government services',
  6: 'Occupations in art, culture, recreation and sport',
  7: 'Sales and service occupations',
  8: 'Trades, transport and equipment operators and related occupations',
  9: 'Natural resources, agriculture and related production occupations',
  10: 'Occupations in manufacturing and utilities'},
 'NOC_43': {1: 'Senior management occupations',
  2: 'Specialized middle management occupations',
  3: 'Middle management occupations in retail and wholesale trade and customer services',
  4: 'Middle management occupations in trades, transportation, production and utilities',
  5: 'Professional occupations in business and finance',
  6: 'Administrative and financial supervisors and administrative occupations',
  7: 'Finance, insurance and related business administrative occupations',
  8: 'Office support occupations',
  9: 'Distribution, tracking and scheduling co-ordination occupations',
  10: 'Professional occupations in natural and applied sciences',
  11: 'Technical occupations related to natural and applied sciences',
  12: 'Professional occupations in nursing',
  13: 'Professional occupations in health (except nursing)',
  14: 'Technical occupations in health',
  15: 'Assisting occupations in support of health services',
  16: 'Professional occupations in education services',
  17: 'Professional occupations in law and social, community and government services',
  18: 'Paraprofessional occupations in legal, social, community and education services',
  19: 'Occupations in front-line public protection services',
  20: 'Care providers and educational, legal and public protection support occupations',
  21: 'Professional occupations in art and culture',
  22: 'Technical occupations in art, culture, recreation and sport',
  23: 'Retail sales supervisors and specialized sales occupations',
  24: 'Service supervisors and specialized service occupations',
  25: 'Sales representatives and salespersons - wholesale and retail trade',
  26: 'Service representatives and other customer and personal services occupations',
  27: 'Sales support occupations',
  28: 'Service support and other service occupations, n.e.c.',
  29: 'Industrial, electrical and construction trades',
  30: 'Maintenance and equipment operation trades',
  31: 'Other installers, repairers and servicers and material handlers',
  32: 'Transport and heavy equipment operation and related maintenance occupations',
  33: 'Trades helpers, construction labourers and related occupations',
  34: 'Supervisors and technical occupations in natural resources, agriculture and related production',
  35: 'Workers in natural resources, agriculture and related production',
  36: 'Harvesting, landscaping and natural resources labourers',
  37: 'Processing, manufacturing and utilities supervisors and central control operators',
  38: 'Processing and manufacturing machine operators and related production workers',
  39: 'Assemblers in manufacturing',
  40: 'Labourers in processing, manufacturing and utilities'},
 'YABSENT': {0: 'Other reasons',
  1: 'Own illness or disability',
  2: 'Personal or family responsibilities',
  3: 'Vacation'},
 'WKSAWAY': {},
 'PAYAWAY': {1: 'Yes', 2: 'No'},
 'UHRSMAIN': {},
 'AHRSMAIN': {},
 'FTPTMAIN': {1: 'Full-time', 2: 'Part-time'},
 'UTOTHRS': {},
 'ATOTHRS': {},
 'HRSAWAY': {},
 'YAWAY': {0: 'Other reasons',
  1: 'Own illness or disability',
  2: 'Personal or family responsibilities',
  3: 'Vacation or civic holiday',
  4: 'Working short-time'},
 'PAIDOT': {},
 'UNPAIDOT': {},
 'XTRAHRS': {},
 'WHYPT': {0: 'Other reasons',
  1: 'Own illness or disability',
  2: 'Caring for children',
  3: 'Other personal or family responsibilities',
  4: 'Going to school',
  5: 'Personal preference',
  6: 'Business conditions or could not find full-time work, looked for full-time work in last month',
  7: 'Business conditions or could not find full-time work, did not look for full-time work in last month'},
 'TENURE': {},
 'PREVTEN': {},
 'HRLYEARN': {},
 'UNION': {1: 'Union member',
  2: 'Not a member but covered by a union contract or collective agreement',
  3: 'Non-unionized'},
 'PERMTEMP': {1: 'Permanent',
  2: 'Temporary, seasonal job',
  3: 'Temporary, term or contract job',
  4: 'Temporary, casual or other temorary jobs'},
 'ESTSIZE': {1: 'Less than 20 employees',
  2: '20 to 99 employees',
  3: '100 to 500 employees',
  4: 'More than 500 employees'},
 'FIRMSIZE': {1: 'Less than 20 employees',
  2: '20 to 99 employees',
  3: '100 to 500 employees',
  4: 'More than 500 employees'},
 'DURUNEMP': {},
 'FLOWUNEM': {1: 'Job losers, temporary layoff',
  2: 'Job losers, permanent layoff',
  3: 'Job leavers',
  4: 'Job leavers/losers (status unknown), worked more than 1 year ago',
  5: 'New entrants',
  6: 'Re-entrants, worked 1 year ago or less',
  7: 'Re-entrants, worked more than 1 year ago',
  8: 'Future starts'},
 'UNEMFTPT': {1: 'Full-time', 2: 'Part-time', 3: 'Future starts'},
 'WHYLEFTO': {0: 'Job leavers, other reasons',
  1: 'Job leavers, own illness or disability',
  2: 'Job leavers, personal or family responsibilities',
  3: 'Job leavers, going to school',
  4: 'Job losers, laid off',
  5: 'Job leavers, retired'},
 'WHYLEFTN': {0: 'Job leavers, other reasons',
  1: 'Job leavers, own illness or disability',
  2: 'Job leavers, caring for children',
  3: 'Job leavers, pregnancy',
  4: 'Job leavers, personal or family responsibilities',
  5: 'Job leavers, going to school',
  6: 'Job leavers, dissatisfied',
  7: 'Job leavers, retired',
  8: 'Job leavers, business sold or closed down (self-employed)',
  9: 'Job losers, end of seasonal job (employee)',
  10: 'Job losers, end of temporary or casual (employee)',
  11: 'Job losers, company moved or out of business (employee)',
  12: 'Job losers, business conditions (employee)',
  13: 'Job losers, dismissal or other reasons'},
 'DURJLESS': {},
 'AVAILABL': {1: 'Not available', 2: 'Yes, available'},
 'LKPUBAG': {1: 'Yes'},
 'LKEMPLOY': {1: 'Yes'},
 'LKRELS': {1: 'Yes'},
 'LKATADS': {1: 'Yes'},
 'LKANSADS': {1: 'Yes'},
 'LKOTHERN': {1: 'Yes'},
 'PRIORACT': {0: 'Other',
  1: 'Working',
  2: 'Managing a home',
  3: 'Going to school'},
 'YNOLOOK': {0: 'Wanted work, reason - other',
  1: 'Wanted work, reason - own illness or disability',
  2: 'Wanted work, reason - caring for children',
  3: 'Wanted work, reason - other personal or family responsibilities',
  4: 'Wanted work, reason - school',
  5: 'Wanted work, reason - awaiting recall or reply',
  6: 'Wanted work, reason - discouraged'},
 'TLOLOOK': {1: 'Yes', 2: 'No'},
 'SCHOOLN': {1: 'Non-student', 2: 'Full-time student', 3: 'Part-time student'},
 'EFAMTYPE': {1: 'Person not in an economic family',
  2: 'Dual-earner couple, no children or none under 25',
  3: 'Dual-earner couple, youngest child 0 to 17',
  4: 'Dual-earner couple, youngest child 18 to 24',
  5: 'Single-earner couple, male employed, no children or none under 25',
  6: 'Single-earner couple, male employed, youngest child 0 to 17',
  7: 'Single-earner couple, male employed, youngest child 18 to 24',
  8: 'Single-earner couple, female employed, no children or none under 25',
  9: 'Single-earner couple, female employed, youngest child 0 to 17',
  10: 'Single-earner couple, female employed, youngest child 18 to 24',
  11: 'Non-earner couple, no children or none under 25',
  12: 'Non-earner couple, youngest child 0 to 17',
  13: 'Non-earner couple, youngest child 18 to 24',
  14: 'Lone-parent family, parent employed, youngest child 0 to 17',
  15: 'Lone-parent family, parent employed, youngest child 18 to 24',
  16: 'Lone-parent family, parent not employed, youngest child 0 to 17',
  17: 'Lone-parent family, parent not employed, youngest child 18 to 24',
  18: 'Other families'},
 'AGYOWNK': {1: 'Youngest child less than 6 years',
  2: 'Youngest child 6 to 12 years',
  3: 'Youngest child 13 to 17 years',
  4: 'Youngest child 18 to 24 years'},
 'FINALWT': {}}

# 2. Extract Information in all Syntax Files

We apply the same procedure to all syntax files now.

In [11]:
varlab = dict()
vallab = dict()
for sf in syntax_files:
    with open('data/{}'.format(sf), 'rt', encoding='utf-8-sig') as f:
        syntax = f.read()
    varlab_syntax = proc_re['varlab'].search(syntax).group(0)
    varlab_syntax = proc_re['varlab_var'].findall(varlab_syntax)
    varlab_syntax = {v: a if a else b for v, a, b in varlab_syntax}
    varlab[sf] = varlab_syntax
    vallab_syntax = proc_re['vallab'].search(syntax).group(0)
    vallab_syntax = proc_re['vallab_var'].findall(vallab_syntax)
    vallab_syntax = {v: l for v, l in vallab_syntax}
    vallab_syntax = {v: {int(n): a if a else b for n, a, b, in proc_re['vallab_lab'].findall(l)} for v, l in vallab_syntax.items()}
    vallab[sf] = vallab_syntax

One way to display all information and to see whether codes have changed meaning over time is to display the data in a table.
First are the variable labels.

In [12]:
pd.DataFrame.from_dict(varlab)

,syntax_2022_rebase2023.txt,syntax_2021_rebase2023.txt,syntax_2020_rebase2023.txt,syntax_2019_rebase2023.txt,syntax_2018_rebase2023.txt,syntax_2017_rebase2023.txt,syntax_2016_rebase2023.txt,syntax_2015_rebase2023.txt,syntax_2014_rebase2023.txt,syntax_2013_rebase2023.txt,...,syntax_2010_rebase2023.txt,syntax_2009_rebase2023.txt,syntax_2008_rebase2023.txt,syntax_2007_rebase2023.txt,syntax_2006_rebase2023.txt,syntax_2000-2010_rebase2001.txt,syntax_1999-nov-dec_rebase2001.txt,syntax_1999-jan-oct_rebase2001.txt,syntax_1987-1998_rebase2001.txt,syntax_1976-1986_rebase2001.txt
REC_NUM,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,...,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file,Order of record in file
SURVYEAR,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,...,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year,Survey year
SURVMNTH,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,...,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month,Survey month
LFSSTAT,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,...,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status,Labour force status
PROV,Province,Province,Province,Province,Province,Province,Province,Province,Province,Province,...,Province,Province,Province,Province,Province,Province,Province,Province,Province,Province
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SP_UHRST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"Spouse's usual hours at ALL jobs, employed","Spouse's usual hours at ALL jobs, employed","Spouse's usual hours at ALL jobs, employed","Spouse's usual hours at ALL jobs, employed","Spouse's usual hours at ALL jobs, employed"
SP_COWM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"Spouse's class of worker, main job, employed","Spouse's class of worker, main job, employed","Spouse's class of worker, main job, employed","Spouse's class of worker, main job, employed","Spouse's class of worker, main job, employed"
AGYOWNKN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Age of youngest own child (children),Age of youngest own child (children),Age of youngest own child (children),Age of youngest own child (children),Age of youngest own child (children)
SCH1624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,At least one child age 16 to 24 in school,At least one child age 16 to 24 in school,At least one child age 16 to 24 in school,At least one child age 16 to 24 in school,At least one child age 16 to 24 in school
FWEIGHT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Final individual or family weight (Integer),Final individual or family weight (Integer),Final individual or family weight (Integer),Final individual or family weight (Integer),Final individual or family weight (Integer)

Second are the value labels.

In [13]:
pd.concat([pd.DataFrame.from_dict(data, orient='index').stack().rename(file) for file, data in vallab.items()], axis=1)

           syntax_2022_rebase2023.txt syntax_2021_rebase2023.txt
SURVMNTH 1                    January                    January  \
         2                   February                   February
         3                      March                      March
         4                      April                      April
         5                        May                        May
...                               ...                        ...
AGYOWNKN 3                        NaN                        NaN
         4                        NaN                        NaN
         5                        NaN                        NaN
         6                        NaN                        NaN
SCH1624  1                        NaN                        NaN

           syntax_2020_rebase2023.txt syntax_2019_rebase2023.txt
SURVMNTH 1                    January                    January  \
         2                   February                   February
         3                      March                      March
         4                      April                      April
         5                        May                        May
...                               ...                        ...
AGYOWNKN 3                        NaN                        NaN
         4                        NaN                        NaN
         5                        NaN                        NaN
         6                        NaN                        NaN
SCH1624  1                        NaN                        NaN

           syntax_2018_rebase2023.txt syntax_2017_rebase2023.txt
SURVMNTH 1                    January                    January  \
         2                   February                   February
         3                      March                      March
         4                      April                      April
         5                        May                        May
...                               ...                        ...
AGYOWNKN 3                        NaN                        NaN
         4                        NaN                        NaN
         5                        NaN                        NaN
         6                        NaN                        NaN
SCH1624  1                        NaN                        NaN

           syntax_2016_rebase2023.txt syntax_2015_rebase2023.txt
SURVMNTH 1                    January                    January  \
         2                   February                   February
         3                      March                      March
         4                      April                      April
         5                        May                        May
...                               ...                        ...
AGYOWNKN 3                        NaN                        NaN
         4                        NaN                        NaN
         5                        NaN                        NaN
         6                        NaN                        NaN
SCH1624  1                        NaN                        NaN

           syntax_2014_rebase2023.txt syntax_2013_rebase2023.txt  ...
SURVMNTH 1                    January                    January  ...  \
         2                   February                   February  ...
         3                      March                      March  ...
         4                      April                      April  ...
         5                        May                        May  ...
...                               ...                        ...  ...
AGYOWNKN 3                        NaN                        NaN  ...
         4                        NaN                        NaN  ...
         5                        NaN                        NaN  ...
         6                        NaN                        NaN  ...
SCH1624  1                        NaN                        NaN  ...

           syntax_2010_rebase2023.txt syntax_2009_rebase2023.txt
SURVMNTH 1                    January                    January  \
         2                   February                   February
         3                      March                      March
         4                      April                      April
         5                        May                        May
...                               ...                        ...
AGYOWNKN 3                        NaN                        NaN
         4                        NaN                        NaN
         5                        NaN                        NaN
         6                        NaN                        NaN
SCH1624  1                        NaN                        NaN

           syntax_2008_rebase2023.txt syntax_2007_rebase2023.txt
SURVMNTH 1                    January                    January  \
         2                   February                   February
         3                      March                      March
         4                      April                      April
         5                        May                        May
...                               ...                        ...
AGYOWNKN 3                        NaN                        NaN
         4                        NaN                        NaN
         5                        NaN                        NaN
         6                        NaN                        NaN
SCH1624  1                        NaN                        NaN

           syntax_2006_rebase2023.txt
SURVMNTH 1                    January  \
         2                   February
         3                      March
         4                      April
         5                        May
...                               ...
AGYOWNKN 3                        NaN
         4                        NaN
         5                        NaN
         6                        NaN
SCH1624  1                        NaN

                      syntax_2000-2010_rebase2001.txt
SURVMNTH 1                                        NaN  \
         2                                        NaN
         3                                        NaN
         4                                        NaN
         5                                        NaN
...                                               ...
AGYOWNKN 3                        Youngest child 6-12
         4                       Youngest child 13-15
         5                       Youngest child 16-17
         6                       Youngest child 18-24
SCH1624  1  At least one child age 16 to 24 in school

           syntax_1999-nov-dec_rebase2001.txt
SURVMNTH 1                                NaN  \
         2                                NaN
         3                                NaN
         4                                NaN
         5                                NaN
...                                       ...
AGYOWNKN 3                                NaN
         4                                NaN
         5                                NaN
         6                                NaN
SCH1624  1                                NaN

                   syntax_1999-jan-oct_rebase2001.txt
SURVMNTH 1                                        NaN  \
         2                                        NaN
         3                                        NaN
         4                                        NaN
         5                                        NaN
...                                               ...
AGYOWNKN 3                        Youngest child 6-12
         4                       Youngest child 13-15
         5                       Youngest child 16-17
         6                       Youngest child 18-24
SCH1624  1  At least one child age 16 to 24 in school

                      syntax_1987-1998_rebase2001.txt
SURVMNTH 1                                        NaN  \
         2                                        NaN
         3                                        NaN
         4                                        NaN
         5                                        NaN
...                                               ...
AGYOWNKN 3                        Youngest child 6-12
         4                       Youngest child 13-15
         5                       Youngest child 16-17
         6                       Youngest child 18-24
SCH1624  1  At least one child age 16 to 24 in school

                      syntax_1976-1986_rebase2001.txt
SURVMNTH 1                                        NaN
         2                                        NaN
         3                                        NaN
         4                                        NaN
         5                                        NaN
...                                               ...
AGYOWNKN 3                        Youngest child 6-12
         4                       Youngest child 13-15
         5                       Youngest child 16-17
         6                       Youngest child 18-24
SCH1624  1  At least one child age 16 to 24 in school

[622 rows x 22 columns]